### ISSUE TITLE
JIT: IL to IR Decomposition

### ISSUE THREAD

**Issue by Astaelan** [ProtonOS/ProtonLegacy#22]
Orvid needs to fill out the information here on this ticket for IL to IR Decomposition, listing the main tasks.

**Comment by Orvid** [comment]
Well, here's a short list:
~ Synthetic Stack (Done)
~ StackObject Pool (Done)
~ Prefix Flags (Done)
~ Non-IR Instructions (In Progress)
~ IR Instructions (Planned)
~ Inlining (Planned)
~ Optimizations (Planned)
