### ISSUE TITLE
Proton.CLR.KOR

### ISSUE THREAD

**Issue by Astaelan** [ProtonOS/ProtonLegacy#31]
- [x] Basic CLR Required Types
### System
- [x] Action
- [x] ArgumentException
- [x] ArgumentNullException
- [x] ArgumentOutOfRangeException
- [x] ArithmeticException
- [x] Array
- [x] ArrayTypeMismatchException
- [x] AsyncCallback
- [x] Attribute
- [x] AttributeTargets
- [x] AttributeUsageAttribute
- [x] BadImageFormatException
- [x] BitConverter
- [x] Boolean
- [x] Buffer
- [x] Byte
- [x] Char
- [x] CharEnumerator
- [x] Comparison
- [ ] Console
- [x] Converter
- [x] Decimal
- [x] Delegate
- [x] Double
- [x] Enum
- [x] Environment
- [x] Exception
- [x] FlagsAttribute
- [x] FormatException
- [x] Func
- [x] GC
- [x] IAsyncResult
- [x] ICloneable
- [x] IComparable
- [x] ICustomFormatter
- [x] IDisposable
- [x] IEquatable
- [x] IFormatProvider
- [x] IFormattable
- [x] IndexOutOfRangeException
- [x] Int16
- [x] Int32
- [x] Int64
- [x] IntPtr
- [x] InvalidCastException
- [x] InvalidOperationException
- [ ] MarshalByRefObject
- [x] Math
- [x] MulticastDelegate
- [x] MulticastNotSupportedException
- [x] NotImplementedException
- [x] NotSupportedException
- [x] Nullable<>
- [x] NullReferenceException
- [x] NumberFormatter
- [x] Object
- [x] ObjectDisposedException
- [x] OperatingSystem
- [x] OverflowException
- [x] ParamArrayAttribute
- [x] ParseHelper
- [x] PlatformID
- [x] Predicate
- [x] RuntimeArgumentHandle
- [x] RuntimeFieldHandle
- [x] RuntimeMethodHandle
- [x] RuntimeType
- [x] RuntimeTypeHandle
- [x] SByte
- [x] Single
- [x] String
- [x] StringHelper
- [x] SystemException
- [x] TimeSpan
- [x] Tuple<>
- [x] Type
- [x] UInt16
- [x] UInt32
- [x] UInt64
- [x] UIntPtr
- [x] UnauthorizedAccessException
- [x] ValueType
- [x] Version
- [x] Void
### System.Collections
- [x] BitArray
- [x] DictionaryEntry
- [x] ICollection
- [x] IDictionary
- [x] IDictionaryEnumerator
- [x] IEnumerable
- [x] IEnumerator
- [x] IEqualityComparer
- [x] IList
### System.Collections.Generic
- [x] Dictionary<>
- [x] EqualityComparer<>
- [x] ICollection<>
- [x] IDictionary<>
- [x] IEnumerable<>
- [x] IEnumerator<>
- [x] IEqualityComparer<>
- [x] IList<>
- [x] KeyNotFoundException
- [x] KeyValuePair<>
- [x] List<>
### System.Globalization
- [x] CultureInfo
- [x] CultureTypes
- [x] DigitShapes
- [x] NumberFormatInfo
- [x] NumberStyles
- [x] TextInfo
- [x] UnicodeCategory
### System.IO
- [x] EndOfStreamException
- [ ] File
- [x] IOException
- [x] MemoryStream
- [x] SeekOrigin
- [x] Stream
- [ ] StreamWriter
- [ ] TextWriter
### System.Kernel
- [x] HeapAllocator
- [x] Multiboot
- [x] PageAllocator
### System.Reflection
- [x] DefaultMemberAttribute
- [x] MemberInfo
### System.Runtime.CompilerServices
- [x] IndexerNameAttribute
- [x] MethodImplAttribute
- [x] MethodImplOptions
- [x] RuntimeHelpers
### System.Runtime.InteropServices
- [x] InAttribute
- [x] OutAttribute
### System.Runtime.Versioning
- [x] TargetFrameworkAttribute
### System.Text
- [x] ASCIIEncoding
- [x] Encoding
- [x] StringBuilder
- [x] UnicodeEncoding
### System.Threading
- [x] WaitHandle

**Comment by tgiphil** [comment]
:(

**Comment by Astaelan** [comment]
Sorry, life moved on. But it might be interesting to revisit this project based on .NET Core now that it's mainstream.
